version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:
  data_volume:

services:
  backend:
    image: sergeyxx/finance_backend
    env_file: .env
    restart: always
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
      - data_volume:/data/
  gateway:
    image: sergeyxx/finance_gateway
    env_file: .env
    restart: always
    volumes:
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - 8041:80