version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:
  data_volume:

services:
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
      - data_volume:/data/
  gateway:
    build: ./infra/
    ports:
      - 8041:80
    volumes:
      - static_volume:/static/
      - media_volume:/media/