# Generated by Django 3.2 on 2023-12-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coupon_id', models.CharField(max_length=50)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='items.order')),
            ],
        ),
    ]
