# Generated by Django 3.2 on 2023-12-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20231229_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCoupon',
        ),
    ]
